### ISSUE TITLE
How to use ARC for the fully-supervised task?

### ISSUE THREAD

**Issue by RuiFeiHe** [SHI-Labs/Semi-Supervised-Transfer-Learning#3]
Hi, impressed by your work! I'm wondering how you use ARC for the fully-supervised task since there is only one labeled set and ARC computes the MMD between representations from two sets.

**Comment by Walleclipse** [comment]
Hi,
We can easily regard the labeled set as the unlabeled set. So we can compute the MMD between two different batches both from the same labeled sets.
If you set `--num_labels -1 --num_unlabels -1` in [parser.py](https://github.com/SHI-Labs/Semi-Supervised-Transfer-Learning/blob/main/code/parser.py), the `lt_loader` and `ult_loader` in [main.py](https://github.com/SHI-Labs/Semi-Supervised-Transfer-Learning/blob/main/code/main.py) are both the dataloader for whole (labeled) datasets. 
Then we compute the MMD between the batches generated from `lt_loader` and `ult_loader`.  Which can be regarded as the MMD between different batches from the whole labeled datasets.
