### ISSUE TITLE
How to generate the train and test fold on cub_200-2011

### ISSUE THREAD

**Issue by bregmangh** [SHI-Labs/Semi-Supervised-Transfer-Learning#5]
Thanks for your nice work! How to generate the train and test folders on cub_200-2011 when run the codes directly.

**Comment by Walleclipse** [comment]
Hi,
There is a `train_test_split.txt` file in the folder of the data package from the official [link](https://drive.google.com/file/d/1hbzc_P1FuxMkcabkgn9ZKinBwW683j45/view) .
You can split the data according to the  `train_test_split.txt`.
Or just follow the related cub_200-2011 preprocessing [repo](https://github.com/TDeVries/cub2011_dataset).
