### ISSUE TITLE
performance under same setting as FixMatch

### ISSUE THREAD

**Issue by JoyHuYY1412** [SHI-Labs/Semi-Supervised-Transfer-Learning#6]
Hi, thank you for your nice work.

Have you implemented this code on CiFAR without pretraining, that is, the original setting as FixMatch?

Since there is no official code of FixMatch in PyTorch, I hope I can use yours as the reproduction.

**Comment by Walleclipse** [comment]
Hi,

For Fixmatch without pretraining, you need to train the model with `--bn_momentum 0.001` and much larger training `--epochs`, and `--lr` also needs to be tuned. Other parameters are the same as the Fixmatch with pretraining. 
e.g: 
```
data_root="data"
dataset=cifar10
num_labels=40
CUDA_VISIBLE_DEVICES=0 nohup  python -u main.py \
--data_root $data_root --dataset $dataset --num_labels $num_labels --pretrained 0 \
--model wideresnetleaky --depth 28 --widen_factor 2 --l_batch_size 64 --ul_batch_size 448 \   
--lr 0.03 --weight_decay 0.0005 --bn_momentum 0.001  --epochs 10000  \
--coef 1.0 --alg pl --strong_aug true --threshold 0.95 --ema_teacher true  --ema_teacher_factor 0.999 \
--interleave 1  --seed 0 \
>fixmatch_${dataset}_${num_labels}.nohups 2>&1 & 
```
I think you can get comparable performance with the original paper.

If the results is not very good, please also try   `--interleave 0` and tune the` --lr `. It is helpful to try larger `--epochs`.

**Comment by JoyHuYY1412** [comment]
> Hi,
> 
> For Fixmatch without pretraining, you need to train the model with `--bn_momentum 0.001` and much larger training `--epochs`, and `--lr` also needs to be tuned. Other parameters are the same as the Fixmatch with pretraining.
> e.g:
> 
> ```
> data_root="data"
> dataset=cifar10
> num_labels=40
> CUDA_VISIBLE_DEVICES=0 nohup  python -u main.py \
> --data_root $data_root --dataset $dataset --num_labels $num_labels --pretrained 0 \
> --model wideresnetleaky --depth 28 --widen_factor 2 --l_batch_size 64 --ul_batch_size 448 \   
> --lr 0.03 --weight_decay 0.0005 --bn_momentum 0.001  --epochs 10000  \
> --coef 1.0 --alg pl --strong_aug true --threshold 0.95 --ema_teacher true  --ema_teacher_factor 0.999 \
> --interleave 1  --seed 0 \
> >fixmatch_${dataset}_${num_labels}.nohups 2>&1 & 
> ```
> 
> I think you can get comparable performance with the original paper.
> 
> If the results is not very good, please also try `--interleave 0` and tune the`--lr`. It is helpful to try larger `--epochs`.

Thank you so much!
