### ISSUE TITLE
Questions about the setting

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [SHI-Labs/Semi-Supervised-Transfer-Learning#8]
Thank you for your nice work.

I just want to ask about that which the SSL consistency loss used in your AKC/ARC/AKC+ARC in the Papar Table 1.
![WechatIMG11](https://user-images.githubusercontent.com/18485270/126886798-06240596-4683-4a8f-b8c5-36ff506982d3.png)

I guess it is the basic threshold-based Pseudo-labeling without sharpening(MixMatch) or Argmax (Fixmatch).

**Comment by Walleclipse** [comment]
Hi,
In the table, the method of "AKC", "ARC", and "AKC+ARC" did not use any other SSL consistency loss (only using AKC or/and ARC in our [paper](http://arxiv.org/abs/2103.02193)).
The method of "MixMatch+AKC+ARC" used the additional SSL consistency loss in MixMatch, and "Fixmatch +AKC+ARC" used the additional SSL consistency loss in Fixmatch paper (similar to threshold-based Pseudo-labeling with strong data augmentation).

**Comment by ZhangYuanhan-AI** [comment]
Ok, I see. So in other words, AKC+ARC(Labeled Data and Unlabeled Data)+CE(Labeled Data) can achieve almost SOTA performance?  That's cool!!!

**Comment by Walleclipse** [comment]
Yes,
It is right for CUB-200-2011 dataset, especially for a small amount of unlabeled data.
But for CIFAR-10, also needs to add additional SSL consistency loss.

**Comment by ZhangYuanhan-AI** [comment]
> Yes,
> It is right for CUB-200-2011 dataset, especially for a small amount of unlabeled data.
> But for CIFAR-10, also needs to add additional SSL consistency loss.

I See. Thanks again for this nice work!
